name: Send Telegram Reports

on:
  schedule:
    # Ежедневно в 10:30, 15:00 и 19:00 МСК
    - cron: '30 7 * * *'   # 10:30 МСК (07:30 UTC)
    - cron: '0 12 * * *'   # 15:00 МСК (12:00 UTC)
    - cron: '0 16 * * *'   # 19:00 МСК (16:00 UTC)

    # Еженедельно — каждое воскресенье в 12:00 МСК
    - cron: '0 9 * * 0'    # 12:00 МСК (09:00 UTC)

    # Ежемесячно — 30-го числа в 12:00 МСК
    - cron: '0 9 30 * *'   # 12:00 МСК (09:00 UTC)
    - cron: '0 9 28 2 *'   # 12:00 МСК (28 февраля, 09:00 UTC)

  workflow_dispatch:
    inputs:
      kind:
        description: 'Тип отчёта: daily | weekly | monthly'
        required: true
        default: 'daily'

jobs:
  send-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: pip install pytz requests

      - name: Define KIND
        id: kind
        run: |
          if [[ "${{ github.event.schedule }}" == "30 7 * * *" || \
                "${{ github.event.schedule }}" == "0 12 * * *" || \
                "${{ github.event.schedule }}" == "0 16 * * *" ]]; then
            echo "kind=daily" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event.schedule }}" == "0 9 * * 0" ]]; then
            echo "kind=weekly" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event.schedule }}" == "0 9 30 * *" || \
                  "${{ github.event.schedule }}" == "0 9 28 2 *" ]]; then
            echo "kind=monthly" >> $GITHUB_OUTPUT
          else
            echo "kind=${{ github.event.inputs.kind }}" >> $GITHUB_OUTPUT
          fi

      - name: Run report
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          KIND: ${{ steps.kind.outputs.kind }}
        run: python report.py
